[build]
builder = "nixpacks"

[build.environment]
NIXPACKS_BUILD_COMMAND = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"

[deploy.environment]
PORT = "8000"